/**
 * German string catalog for all user-facing text.
 * Ported from frontend/strings.js, minus dead strings and bridge-specific errors.
 *
 * Reference: F-TS06 §7 (German String Catalog)
 */

export const SHELL_TABS = ["season", "standings", "import", "corrections", "history"] as const;
export type ShellTab = (typeof SHELL_TABS)[number];

export const STR = {
  shell: {
    appTitle: "Stundenlauf-Auswertung",
    tabs: {
      season: "Saison",
      standings: "Auswertung",
      import: "Import",
      corrections: "Korrekturen",
      history: "Historie",
    } as Record<ShellTab, string>,
    seasonLabelPlaceholder: "Saison: -",
    reviewLabelPlaceholder: "Offene Prüfungen: 0",
    seasonSelectLabel: "Aktuelle Saison:",
    reviewLabel: "Offene Prüfungen:",
    noSeasonOption: "Keine Saison",
    sectionsTitle: "Bereiche",
    defaultControlHint: {
      season: "Bereichsspezifische Saison-Steuerungen erscheinen hier.",
      standings: "Steuerungen fuer die Auswertung werden geladen.",
      import: "Bereichsspezifische Import-Steuerungen erscheinen hier.",
      corrections: "Bereichsspezifische Korrektur-Steuerungen erscheinen hier.",
      history: "Bereichsspezifische Historie-Steuerungen erscheinen hier.",
    } as Record<ShellTab, string>,
  },
  status: {
    prefix: "Status:",
    defaultReady: "Bereit",
    appLoading: "Oberflaeche wird geladen...",
  },
  confirmModal: {
    confirm: "Bestätigen",
    cancel: "Abbrechen",
    closeAria: "Dialog schließen",
  },
  views: {
    standings: {
      title: "Aktuelle Wertung",
      subtitle: "Wählen Sie eine Kategorie aus und prüfen Sie die aktuellen Tabellenstände.",
      placeholder: "Noch keine Daten in dieser Kategorie.",
      noSeason: "Bitte zuerst eine Saison auswählen.",
      categoriesTitle: "Kategorien",
      summaryTitle: "Übersicht",
      exportTitle: "Exporte",
      modeOverview: "Übersicht",
      modeCorrectIdentity: "Identität korrigieren",
      modeMergeDuplicates: "Duplikate zusammenführen",
      exportPdf: "PDF exportieren",
      exportExcel: "Excel exportieren",
      raceOverviewTitle: "Laufübersicht",
      overallTitle: "Gesamtwertung",
      importedRunsTitle: "Importierte Läufe",
      importedRunsSubtitle: "Diese Liste zeigt die zuletzt berücksichtigten Läufe der Saison.",
      importedRunsRowSingles: "Einzel",
      importedRunsRowCouples: "Paare",
      importedRunsRaceCol: "Lauf",
      importedRunsCategoryCol: "Kategorie",
      importedRunsDateCol: "Datum",
      importedRunsFileCol: "Datei",
      importedRunsEntriesCol: "Einträge",
      noCategory: "Keine Kategorie vorhanden.",
      noRows: "Noch keine Wertungsdaten vorhanden.",
      rank: "Rang",
      team: "Team",
      club: "Verein",
      points: "Punkte",
      distance: "Distanz (km)",
      races: "Läufe",
      participants: "Teilnehmende",
      totalTeams: "Teams",
      totalRuns: "Läufe gesamt",
      lastUpdated: "Letzte Aktualisierung",
      note: "Hinweis",
      statusExcluded: "außer Wertung",
      selectPerson: "Person auswählen",
      identitySaved: "Identität gespeichert.",
      mergeSaved: "Duplikate zusammengeführt.",
      sectionSingles: "Einzel",
      sectionCouples: "Paare",
      detailResultsTitle: "Detailergebnisse",
      loading: "Wertungen werden geladen...",
      headerRank: "Platz",
      headerName: "Name",
      headerYob: "Jahrgang",
      headerExcluded: "a.W.",
      headerTotalDistanceKm: "Gesamtdistanz (km)",
      headerTotalDistance: "Gesamtdistanz",
      headerTotalPoints: "Gesamtpunkte",
      excludedAria: (team: string) => `a.W. ${team}`,
      exportPdfLong: "Wertungen als PDF speichern",
      exportExcelLong: "Gesamtwertung als Excel speichern",
    },
    import: {
      title: "Lauf Importieren",
      subtitle: "Geführter Ablauf für Datei-Import, Zuordnungsprüfung und Abschluss.",
      flowStepSelect: "1. Datei auswählen",
      flowStepReview: "2. Zuordnungen prüfen",
      flowStepSummary: "3. Zusammenfassung",
      flowCurrent: "Aktueller Schritt",
      selectFileTitle: "Datei und Kontext auswählen",
      selectFileHint: "Wählen Sie Datei, Wettbewerb und Laufnummer. Danach startet die Prüfliste.",
      pickFile: "Datei auswählen",
      fileNameLabel: "Dateiname",
      noFilePlaceholder: "Keine Datei",
      singles: "Einzel",
      couples: "Paare",
      raceNumber: "Laufnummer",
      raceSelectPlaceholder: "Bitte wählen...",
      stepNextToReview: "Weiter zu Zuordnungen",
      stepBackToSelection: "Zurück zu Datei",
      stepBackToReview: "Zurück zu Zuordnungen",
      importRace: "Lauf importieren",
      matchingSettings: "Matching-Einstellungen",
      matchingModeStrict: "Strikt",
      matchingModeFuzzy: "Fuzzy-Automatik",
      matchingModeManual: "Manuell",
      matchingFuzzySubPerfect: "Nur 100 %-Ähnlichkeit",
      matchingFuzzySubThreshold: "Ab Schwelle",
      matchingThresholdLabel: "Ähnlichkeit ab der automatisch zugeordnet wird",
      matchingReviewThresholdLabel: "Mindest-Ähnlichkeit für Prüfliste",
      effectiveAutoThresholdLabel: "Effektive Auto-Schwelle",
      matchingHintStrict:
        "Automatische Zuordnung nur bei exakter normalisierter Identität (Name, Jahrgang, Verein, Geschlecht).",
      matchingHintFuzzyPerfect: "Automatische Zuordnung nur bei 100 % Treffersicherheit.",
      matchingHintFuzzyThreshold:
        "Automatische Zuordnung ab eingestellter Schwelle, darunter Prüfliste oder neue Identität.",
      matchingHintManual:
        "Keine automatische Zuordnung über Ähnlichkeit, alle unsicheren Fälle landen in der Prüfliste.",
      reviewTitle: "Zusammenführungen prüfen",
      noOpenReviews: "Keine offenen Prüfungen.",
      reviewProgress: (current: number, total: number) => `Prüfung ${current} von ${total}`,
      reviewProgressShort: (current: number, total: number) => `Zuordnung ${current} von ${total}`,
      reviewHintLayout:
        "Oben sehen Sie den eingehenden Eintrag. Darunter vorhandene Kandidaten nach Treffersicherheit.",
      reviewHintNoMatch:
        'Wenn kein Kandidat passt, wählen Sie "Keine passt: neue Person anlegen".',
      reviewBackEntry: "Vorherige Zuordnung",
      reviewNextEntry: "Nächste Zuordnung",
      reviewTypoFix: "Zusammenführen und Namen korrigieren",
      reviewCreateNewTitle: "Neue Person anlegen",
      reviewCreateNewDescription:
        "Die importierte Person wird als neuer Datensatz übernommen. Es erfolgt keine Zusammenführung.",
      reviewRecommended: "Empfohlen",
      incomingHeading: "Neuer eingehender Eintrag",
      candidatesHeading: "Mögliche Treffer (beste Übereinstimmung zuerst)",
      mergeAccept: "Mit ausgewählter Person/Team zusammenführen",
      mergeNewIdentity: "Keine passt: neue Person anlegen",
      summaryTitle: "Import-Zusammenfassung",
      summaryHint: "Prüfen Sie die Ergebnisse. Erst mit Abschluss wird der Lauf gespeichert.",
      summaryImportedEntries: "Importierte Einträge",
      summaryMergedEntries: "Zusammengeführt",
      summaryNewPersons: "Neue Personen",
      summaryTypoFixes: "Namenskorrekturen",
      summaryWarnings: "Warnungen",
      summaryNoWarnings: "Keine Warnungen.",
      finalizeImport: "Import abschließen",
      importBlockedByOpenReviews:
        "Solange offene Zusammenführungs-Prüfungen bestehen, kann kein weiterer Lauf importiert werden.",
      importBlockedOpenReviewsShort:
        "Es gibt offene Prüfungen. Bitte zuerst die aktuelle Prüfliste abschließen.",
      importIncomplete: "Bitte Datei, Lauftyp und Laufnummer vollständig wählen.",
      importRunning: "Import läuft...",
      importDone: "Import abgeschlossen.",
      importDoneWithReviews: "Import abgeschlossen. Bitte prüfen Sie offene Zuordnungen.",
      importFailed: "Import konnte nicht abgeschlossen werden.",
      importDraftFailed: "Import-Entwurf konnte nicht erstellt werden.",
      raceWord: "Lauf",
      inferenceDetectedBoth: (typeLabel: string, racePart: string) => `Erkannt: ${typeLabel} · ${racePart}`,
      inferenceDetectedTypeOnly: (typeLabel: string) =>
        `Erkannt: ${typeLabel} · Laufnummer nicht im Dateinamen, bitte wählen.`,
      reviewIncoming: "Eingehend",
      reviewName: "Name",
      reviewYob: "Jahrgang",
      reviewClub: "Verein",
      reviewConfidence: "Treffer %",
      reviewAction: "Aktion",
      reviewNoCandidates: "Keine Kandidaten vorhanden",
      filePlaceholder: "lauf4-mw.xlsx",
      racePlaceholder: "4",
      filePickButton: "Datei wählen",
      helpTitle: "Hilfe",
      helpDescription: "Wählen Sie Datei, Wettbewerb und Laufnummer.",
      fileCheckTitle: "Datei-Prüfung",
      fileDetected: "Datei erkannt ✅",
      fileMissing: "Datei fehlt",
      fileTypeValid: "Excel-Datei gültig ✅",
      fileTypePending: "Dateityp wird nach Start geprüft",
      raceSelected: (race: number) => `Laufnummer ${race} gewählt`,
      raceMissing: "Laufnummer fehlt",
      raceOccupied: "Laufnummer bereits belegt",
      raceFree: "Laufnummer frei ✅",
      racePending: "Laufnummer noch offen",
      nextStepTitle: "Nächster Schritt",
      nextStepDescription: "Danach prüfen Sie mögliche Zuordnungen.",
      summaryNext: "Zusammenfassung ➡️",
      fixData: "✍️ Daten korrigieren",
      incomingStartNumber: "Startnr.",
      incomingResult: "Wertung",
      createNewSelected: "ausgewählt",
      noVisibleCandidates:
        "Für den aktuellen Modus gibt es keine sichtbaren Kandidaten. Prüfen Sie die Matching-Optionen.",
      progressTitle: "Fortschritt",
      completedCount: (count: number) => `${count} erledigt`,
      openCount: (count: number) => `${count} offen`,
      matchingOptionsTitle: "Matching-Optionen",
      matchingModeAria: "Matching-Modus",
      matchingModeShortFuzzy: "Fuzzy",
      autoThresholdLabel: (value: string) => `Auto-Schwelle (${value})`,
      reviewThresholdLabel: (value: string) => `Prüf-Schwelle (${value})`,
      matchingModeHintStrict: "Strikt zeigt nur exakte Treffer.",
      matchingModeHintManual: "Manuell zeigt alle Kandidaten ohne Auto-Zuordnung.",
      matchingModeHintAutoZone: "Fuzzy-Automatik: oberster Treffer liegt in der Auto-Zone.",
      matchingModeHintReviewList: "Fuzzy-Automatik: oberster Treffer bleibt in der Prüfliste.",
      visibleCandidatesCount: (visible: number, total: number) => `Sichtbare Kandidaten: ${visible} von ${total}`,
      hintsTitle: "Hinweise",
      hintCheckYob: "Prüfen Sie Jahrgang bei Unsicherheit.",
      hintClubChanged: "Verein kann sich geändert haben.",
      hintNextCase: "Der nächste offene Fall wird danach geladen.",
      resultTitle: "Ergebnis",
      resultDescription: "Nach dem Abschluss wird die Saisonwertung aktualisiert.",
      noteTitle: "Hinweis",
      noteDescription: "Alle Änderungen erscheinen in der Historie.",
      selectedSuffix: "ausgewählt",
    },
    history: {
      title: "Historie",
      subtitle: "Die Historienansicht folgt in Phase 3 der Migration.",
      placeholder: "Noch keine Historie vorhanden.",
      importHistoryTitle: "Import-Historie",
      auditTrailTitle: "Audit-Protokoll",
      sourceFile: "Quelle",
      importedAt: "Importiert am",
      state: "Status",
      rows: "Zeilen",
      rollback: "Rollback",
      noImports: "Keine Imports vorhanden.",
      noAuditRows: "Keine Korrekturen protokolliert.",
      rollbackConfirmTitle: "Import zurückrollen?",
      rollbackConfirmBody:
        "Der ausgewählte Import und zugehörige Läufe werden als zurückgerollt markiert.",
      rollbackConfirmBodyWithCount: (count: number) =>
        `Die Ergebnisse aller ${count} Läufe aus dieser Datei werden aus der Wertung entfernt und neu berechnet.`,
      rollbackDone: (count: number) => `Datei-Import wurde zurückgenommen (${count} Läufe).`,
      rolledBack: "zurückgerollt",
      active: "aktiv",
    },
    season: {
      title: "Saison verwalten",
      subtitle: "Wählen Sie eine bestehende Saison aus oder legen Sie eine neue Saison an.",
      placeholder: "Bitte Saison auswählen oder neu anlegen.",
      createTitle: "Neue Saison",
      createLabel: "Saisonname",
      createAction: "Neue Saison erstellen",
      openAction: "Öffnen",
      deleteAction: "Löschen",
      resetAction: "Zurücksetzen",
      importAction: "Saison importieren",
      exportAction: "Saison exportieren",
      noSeasons: "Noch keine Saisons vorhanden.",
      activeTag: "Aktiv",
      importedEvents: "Importierte Läufe",
      lastModified: "Zuletzt geändert",
      actions: "Aktionen",
      deleteConfirmTitle: "Saison löschen?",
      deleteConfirmBody: "Diese Saison wird dauerhaft entfernt.",
      resetConfirmTitle: "Saison zurücksetzen?",
      resetConfirmBody: "Alle Event-Daten der Saison werden gelöscht.",
      exportHint: "Export folgt in F-TS07/F-TS08.",
      importHint: "Import folgt in F-TS07.",
      createdDone: (label: string) => `Saison "${label}" angelegt.`,
      deletedDone: "Saison gelöscht.",
      resetDone: "Saison wurde zurückgesetzt.",
      openedDone: (label: string) => `Saison "${label}" geöffnet.`,
      nameHeader: "Name",
      createPlaceholder: "z. B. Stundenlauf 2027",
      activeSeasonTitle: "Aktive Saison",
      noActiveSeason: "Noch keine Saison geoeffnet.",
      backupNote:
        "Backup-Import und Backup-Export sind in Phase 1 bereits sichtbar, werden aber noch vom Mock-AppApi beantwortet.",
      existingSeasonsTitle: "Bestehende Saisons",
      existingSeasonsDescription: "Alle vorhandenen Saisons stehen hier direkt zum Oeffnen oder Verwalten bereit.",
      loading: "Saisons werden geladen...",
      enterSeasonName: "Bitte einen Saisonnamen eingeben.",
    },
    corrections: {
      title: "Korrekturen",
      subtitle: "Echte Korrekturabläufe folgen in einer späteren Migrationsphase.",
      placeholder: "Für Phase 1 bleibt dieser Bereich bewusst als Platzhalter bestehen.",
    },
  },
  category: {
    "hour:men": "60 Minuten Herren",
    "hour:women": "60 Minuten Damen",
    "hour:couples_men": "60 Minuten Paare Herren",
    "hour:couples_women": "60 Minuten Paare Damen",
    "hour:couples_mixed": "60 Minuten Paare Mixed",
    "half_hour:men": "30 Minuten Herren",
    "half_hour:women": "30 Minuten Damen",
    "half_hour:couples_men": "30 Minuten Paare Herren",
    "half_hour:couples_women": "30 Minuten Paare Damen",
    "half_hour:couples_mixed": "30 Minuten Paare Mixed",
  } as Record<string, string>,
  actions: {
    save: "Speichern",
    close: "Schließen",
    apply: "Übernehmen",
  },
  identityModal: {
    title: "Identität korrigieren",
    givenName: "Vorname",
    familyName: "Nachname",
    displayName: "Anzeigename",
    yob: "Jahrgang",
    club: "Verein",
  },
  mergeModal: {
    title: "Duplikate zusammenführen",
    survivor: "Ziel-Team",
    absorbed: "Aufzulösendes Team",
    help: "Alle übertragbaren Einträge werden vom aufzulösenden Team zum Ziel-Team verschoben.",
  },
  confidence: {
    high: "hoch",
    medium: "mittel",
    low: "niedrig",
  },
  app: {
    errorTitle: "App-Fehler",
  },
  update: {
    available: "Neue Version verfuegbar.",
    refresh: "Aktualisieren",
  },
  importCandidate: {
    incomingLabel: "Neu:",
    existingLabel: "Bestand:",
    participantA: "Teilnehmende A",
    participantB: "Teilnehmende B",
    name: "Name",
    yob: "Jahrgang",
    club: "Verein",
    assignmentHint: "Bei Auswahl werden die eingehenden Ergebnisse dieser Person bzw. diesem Team zugeordnet.",
    confidencePercent: (value: number) => `${value} % Treffer`,
    selectedDisplayName: (name: string, suffix: string) => `${name} - ${suffix}`,
  },
} as const;
