/**
 * German string catalog for all user-facing text.
 * Ported from frontend/strings.js, minus dead strings and bridge-specific errors.
 *
 * Reference: F-TS06 §7 (German String Catalog)
 */

export const SHELL_TABS = ["season", "standings", "import", "corrections", "history"] as const;
export type ShellTab = (typeof SHELL_TABS)[number];

export const STR = {
  shell: {
    appTitle: "Stundenlauf-Auswertung",
    tabs: {
      season: "Saison",
      standings: "Auswertung",
      import: "Import",
      corrections: "Korrekturen",
      history: "Historie",
    } as Record<ShellTab, string>,
    seasonLabelPlaceholder: "Saison: -",
    reviewLabelPlaceholder: "Offene Prüfungen: 0",
    seasonSelectLabel: "Aktuelle Saison:",
    reviewLabel: "Offene Prüfungen:",
    noSeasonOption: "Keine Saison",
    sectionsTitle: "Bereiche",
  },
  status: {
    prefix: "Status:",
    defaultReady: "Bereit",
    appLoading: "Oberflaeche wird geladen...",
  },
  confirmModal: {
    confirm: "Bestätigen",
    cancel: "Abbrechen",
    closeAria: "Dialog schließen",
  },
  views: {
    standings: {
      title: "Aktuelle Wertung",
      subtitle: "Wählen Sie eine Kategorie aus und prüfen Sie die aktuellen Tabellenstände.",
      placeholder: "Noch keine Daten in dieser Kategorie.",
      noSeason: "Bitte zuerst eine Saison auswählen.",
      categoriesTitle: "Kategorien",
      summaryTitle: "Übersicht",
      exportTitle: "Exporte",
      modeOverview: "Übersicht",
      modeCorrectIdentity: "Identität korrigieren",
      modeMergeDuplicates: "Duplikate zusammenführen",
      exportPdf: "PDF exportieren",
      exportExcel: "Excel exportieren",
      raceOverviewTitle: "Laufübersicht",
      overallTitle: "Gesamtwertung",
      importedRunsTitle: "Importierte Läufe",
      importedRunsSubtitle: "Diese Liste zeigt die zuletzt berücksichtigten Läufe der Saison.",
      importedRunsRowSingles: "Einzel",
      importedRunsRowCouples: "Paare",
      importedRunsRaceCol: "Lauf",
      importedRunsCategoryCol: "Kategorie",
      importedRunsDateCol: "Datum",
      importedRunsFileCol: "Datei",
      importedRunsEntriesCol: "Einträge",
      noCategory: "Keine Kategorie vorhanden.",
      noRows: "Noch keine Wertungsdaten vorhanden.",
      rank: "Rang",
      team: "Team",
      club: "Verein",
      points: "Punkte",
      distance: "Distanz (km)",
      races: "Läufe",
      participants: "Teilnehmende",
      totalTeams: "Teams",
      totalRuns: "Läufe gesamt",
      lastUpdated: "Letzte Aktualisierung",
      note: "Hinweis",
      statusExcluded: "außer Wertung",
      statusIncluded: "In Wertung aufgenommen",
      selectPerson: "Person auswählen",
      identitySaved: "Identität gespeichert.",
      mergeSaved: "Duplikate zusammengeführt.",
      sectionSingles: "Einzel",
      sectionCouples: "Paare",
      detailResultsTitle: "Detailergebnisse",
      loading: "Wertungen werden geladen...",
      headerRank: "Platz",
      headerName: "Name",
      headerYob: "Jahrgang",
      headerExcluded: "a.W.",
      headerTotalDistanceKm: "Gesamtdistanz (km)",
      headerTotalDistance: "Gesamtdistanz",
      headerTotalPoints: "Gesamtpunkte",
      excludedAria: (team: string) => `a.W. ${team}`,
      pdfStyleLabel: "PDF-Stil",
      pdfStyleNormal: "Normal",
      pdfStyleCompact: "Kompakt",
      exportPdfLong: "Wertungen als PDF speichern",
      exportExcelLong: "Gesamtwertung als Excel speichern",
      metaLastUpdatedLabel: "zuletzt aktualisiert",
      metaSeparator: " · ",
      kpiTeamsLabel: "Teams in Wertung",
      kpiRacesLabel: "Läufe importiert",
      kpiExcludedLabel: "Außer Wertung",
      kpiRacesValue: (current: number, total: number) => `${current} / ${total}`,
      categoryRowHalfHour: "Halbstunde",
      categoryRowHour: "Stunde",
      headerRaceGroup: (race: number) => `${race}. Lauf`,
      headerTotalGroup: "Gesamt",
      headerUnitKm: "km",
      headerUnitPoints: "Pkt",
      excludedTeamLabel: (team: string) => `Außer Wertung: ${team}`,
    },
    import: {
      title: "Lauf Importieren",
      subtitle: "Geführter Ablauf für Datei-Import, Zuordnungsprüfung und Abschluss.",
      flowStepSelect: "1. Datei auswählen",
      flowStepReview: "2. Zuordnungen prüfen",
      flowStepSummary: "3. Zusammenfassung",
      flowCurrent: "Aktueller Schritt",
      selectFileTitle: "Datei und Kontext auswählen",
      selectFileHint: "Wählen Sie Datei, Wettbewerb und Laufnummer. Danach startet die Prüfliste.",
      seasonOverviewTitle: "Bisher importierte Läufe",
      seasonOverviewHint: "Übersicht der Läufe in der aktuellen Saison. Tippen Sie auf einen freien Lauf, um ihn vorzuwählen.",
      seasonOverviewSinglesLabel: "Einzel",
      seasonOverviewDoublesLabel: "Paare",
      seasonOverviewLegendImported: "importiert",
      seasonOverviewLegendFree: "frei",
      seasonOverviewChipImported: (race: number, category: string) => `${category} Lauf ${race} bereits importiert`,
      seasonOverviewChipFree: (race: number, category: string) => `${category} Lauf ${race} noch frei – auswählen`,
      selectionStatusNoFile: "Wählen Sie zunächst eine Datei aus.",
      selectionStatusDetected: (category: string, race: number) => `Erkannt: ${category} · Lauf ${race}`,
      selectionStatusDetectedSub: "Stimmt das nicht? Wählen Sie links den richtigen Lauf.",
      selectionStatusRaceMissing: (category: string) => `Erkannt: ${category} — Laufnummer nicht im Dateinamen.`,
      selectionStatusRaceMissingSub: "Bitte wählen Sie links den Ziel-Lauf.",
      pickFile: "Datei auswählen",
      fileNameLabel: "Dateiname",
      noFilePlaceholder: "Keine Datei",
      singles: "Einzel",
      couples: "Paare",
      raceNumber: "Laufnummer",
      raceSelectPlaceholder: "Bitte wählen...",
      stepNextToReview: "Weiter zu Zuordnungen",
      stepBackToSelection: "Zurück zu Datei",
      stepBackToReview: "Zurück zu Zuordnungen",
      importRace: "Lauf importieren",
      matchingSettings: "Einstellungen",
      matchingModeStrict: "Strikt",
      matchingModeFuzzy: "Fuzzy-Automatik",
      matchingModeManual: "Manuell",
      matchingFuzzySubPerfect: "Nur 100 %-Ähnlichkeit",
      matchingFuzzySubThreshold: "Ab Schwelle",
      matchingThresholdLabel: "Ähnlichkeit ab der automatisch zugeordnet wird",
      matchingReviewThresholdLabel: "Mindest-Ähnlichkeit für Prüfliste",
      effectiveAutoThresholdLabel: "Effektive Auto-Schwelle",
      matchingHintStrict:
        "Automatische Zuordnung nur bei exakter normalisierter Identität (Name, Jahrgang, Verein, Geschlecht).",
      matchingHintFuzzyPerfect: "Automatische Zuordnung nur bei 100 % Treffersicherheit.",
      matchingHintFuzzyThreshold:
        "Automatische Zuordnung ab eingestellter Schwelle, darunter Prüfliste oder neue Identität.",
      matchingHintManual:
        "Keine automatische Zuordnung über Ähnlichkeit, alle unsicheren Fälle landen in der Prüfliste.",
      noOpenReviews: "Keine offenen Prüfungen.",
      reviewProgress: (current: number, total: number) => `Prüfung ${current} von ${total}`,
      reviewProgressShort: (current: number, total: number) => `Zuordnung ${current} von ${total}`,
      reviewHintLayout:
        "Oben sehen Sie den eingehenden Eintrag. Darunter vorhandene Kandidaten nach Treffersicherheit.",
      reviewHintNoMatch:
        'Wenn kein Kandidat passt, wählen Sie "Keine passt: neue Person anlegen".',
      reviewBackEntry: "Vorige",
      reviewNextEntry: "Nächste",
      reviewTypoFix: "Zusammenführen und Namen korrigieren",
      reviewCreateNewTitle: "Neue Person anlegen",
      reviewCreateNewDescription:
        "Die importierte Person wird als neuer Datensatz übernommen. Es erfolgt keine Zusammenführung.",
      reviewEntryProgress: (current: number, total: number) => `Eintrag ${current}/${total}`,
      candidatesHeading: "Mögliche Treffer (beste Übereinstimmung zuerst)",
      mergeAccept: "Mit ausgewählter Person/Team zusammenführen",
      mergeNewIdentity: "Keine passt: neue Person anlegen",
      summaryTitle: "Import-Zusammenfassung",
      summaryHint: "Prüfen Sie die Ergebnisse. Erst mit Abschluss wird der Lauf gespeichert.",
      summaryImportedEntries: "Importierte Einträge",
      summaryNewPersons: "Neue Personen",
      summaryManualDecisions: "Manuell entschieden",
      summaryContextEyebrow: "Bereit zum Abschluss",
      summaryContextHeadline: (category: string, race: number) => `${category} · Lauf ${race}`,
      summaryContextFileLabel: "Quelle",
      summaryDecisionsTitle: "Manuell entschiedene Zuordnungen",
      summaryDecisionsHint:
        "Diese Einträge wurden in der Prüfliste angezeigt — entweder zugeordnet oder neu angelegt.",
      summaryDecisionsEmpty:
        "Keine manuellen Entscheidungen — alle Einträge wurden automatisch zugeordnet.",
      summaryDecisionsColEntry: "Eingehend",
      summaryDecisionsColAction: "Aktion",
      summaryDecisionsColTarget: "Verknüpft mit",
      summaryDecisionMerge: "🔗 Zusammengeführt",
      summaryDecisionTypoFix: "✍️ Mit Korrektur zusammengeführt",
      summaryDecisionCreateNew: "🆕 Neue Person angelegt",
      summaryDecisionCreateNewTarget: "—",
      finalizeImport: "Import abschließen",
      importBlockedByOpenReviews:
        "Solange offene Zusammenführungs-Prüfungen bestehen, kann kein weiterer Lauf importiert werden.",
      importBlockedOpenReviewsShort:
        "Es gibt offene Prüfungen. Bitte zuerst die aktuelle Prüfliste abschließen.",
      importIncomplete: "Bitte Datei, Lauftyp und Laufnummer vollständig wählen.",
      importRunning: "Import läuft...",
      importDone: "Import abgeschlossen.",
      importDoneWithReviews: "Import abgeschlossen. Bitte prüfen Sie offene Zuordnungen.",
      importFailed: "Import konnte nicht abgeschlossen werden.",
      importDraftFailed: "Import-Entwurf konnte nicht erstellt werden.",
      leaveInProgressTitle: "Import-Prozess verlassen?",
      leaveInProgressConfirm:
        "Der aktuelle Import-/Matching-Prozess ist noch nicht abgeschlossen. Beim Verlassen werden die aktuellen Schritte verworfen.",
      leaveInProgressProceed: "Trotzdem verlassen",
      raceWord: "Lauf",
      inferenceDetectedBoth: (typeLabel: string, racePart: string) => `Erkannt: ${typeLabel} · ${racePart}`,
      inferenceDetectedTypeOnly: (typeLabel: string) =>
        `Erkannt: ${typeLabel} · Laufnummer nicht im Dateinamen, bitte wählen.`,
      reviewIncoming: "Eingehend",
      reviewName: "Name",
      reviewYob: "Jahrgang",
      reviewClub: "Verein",
      reviewAction: "Aktion",
      reviewNoCandidates: "Keine Kandidaten vorhanden",
      filePlaceholder: "lauf4-mw.xlsx",
      racePlaceholder: "4",
      filePickButton: "Datei wählen",
      helpTitle: "Hilfe",
      helpDescription: "Wählen Sie Datei, Wettbewerb und Laufnummer.",
      fileCheckTitle: "Datei-Prüfung",
      fileDetected: "Datei erkannt ✅",
      fileMissing: "Datei fehlt",
      fileTypeValid: "Excel-Datei gültig ✅",
      fileTypePending: "Dateityp wird nach Start geprüft",
      raceSelected: (race: number) => `Laufnummer ${race} gewählt`,
      raceMissing: "Laufnummer fehlt",
      raceOccupied: "Laufnummer bereits belegt",
      raceFree: "Laufnummer frei ✅",
      racePending: "Laufnummer noch offen",
      nextStepTitle: "Nächster Schritt",
      nextStepDescription: "Danach prüfen Sie mögliche Zuordnungen.",
      summaryNext: "Zusammenfassung ➡️",
      fixData: "✍️ Daten korrigieren",
      incomingStartNumber: "Startnr.",
      incomingResult: "Wertung",
      createNewSelected: "ausgewählt",
      noVisibleCandidates:
        "Für den aktuellen Modus gibt es keine sichtbaren Kandidaten. Prüfen Sie die Matching-Optionen.",
      reviewMatchesHeading: "Mögliche Treffer",
      reviewFallbackDivider: "oder",
      reviewFallbackHeading: "Keine Übereinstimmung",
      reviewIncomingEyebrow: "Aktuell zu prüfen",
      reviewIncomingCta:
        "↓ Wählen Sie unten eine passende Person/ein Team — oder legen Sie unten eine neue Person an.",
      progressTitle: "Fortschritt",
      completedCount: (count: number) => `${count} erledigt`,
      openCount: (count: number) => `${count} offen`,
      matchingOptionsTitle: "Matching-Optionen",
      matchingModeAria: "Matching-Modus",
      matchingModeShortFuzzy: "Fuzzy",
      autoThresholdLabel: (value: string) => `Auto-Schwelle (${value})`,
      reviewThresholdLabel: (value: string) => `Prüf-Schwelle (${value})`,
      matchingModeHintStrict: "Strikt zeigt nur exakte Treffer.",
      matchingModeHintManual: "Manuell zeigt alle Kandidaten ohne Auto-Zuordnung.",
      matchingModeHintAutoZone: "Fuzzy-Automatik: oberster Treffer liegt in der Auto-Zone.",
      matchingModeHintReviewList: "Fuzzy-Automatik: oberster Treffer bleibt in der Prüfliste.",
      visibleCandidatesCount: (visible: number, total: number) => `Sichtbare Kandidaten: ${visible} von ${total}`,
      autoSelectTopCandidateLabel: "Ersten Treffer automatisch auswählen",
      autoSelectTopCandidateHint:
        "Wenn aktiviert, wird der beste sichtbare Treffer vorausgewählt. Sonst müssen Sie je Eintrag aktiv einen Treffer oder „Neue Person anlegen“ wählen.",
      reviewAdvanceRequiresDecisionTitle:
        "Bitte wählen Sie einen Treffer oder „Neue Person anlegen“, bevor Sie fortfahren.",
      hintsTitle: "Hinweise",
      hintCheckYob: "Prüfen Sie Jahrgang bei Unsicherheit.",
      hintClubChanged: "Verein kann sich geändert haben.",
      hintNextCase: "Der nächste offene Fall wird danach geladen.",
      resultTitle: "Ergebnis",
      resultDescription: "Nach dem Abschluss wird die Saisonwertung aktualisiert.",
      noteTitle: "Hinweis",
      noteDescription: "Alle Änderungen erscheinen in der Historie.",
      selectedSuffix: "ausgewählt",
    },
    history: {
      title: "Historie",
      subtitle: "Übersicht der importierten Dateien. Hier können Sie den Saisonstand auf den Zeitpunkt vor einem Import zurücksetzen.",
      placeholder: "Noch keine Historie vorhanden.",
      importHistoryTitle: "Import-Historie",
      auditTrailTitle: "Audit-Protokoll",
      selectedRaceTitle: "Ausgewaehlter Lauf",
      selectedRaceEmpty: "Kein Laufkontext vorhanden.",
      selectedRaceAsOf: (seq: number) => `Historischer Stand (seq ${seq})`,
      selectedRaceLive: "Live-Stand",
      freezeHint: "Vorschau aktiv: weitere Aenderungen bleiben gesperrt, bis Sie zur Live-Ansicht wechseln.",
      historyTableTitle: "Import-Übersicht",
      eventType: "Ereignis",
      eventSummary: "Beschreibung",
      eventScope: "Umfang",
      eventEffective: "Wirksam",
      eventActions: "Aktionen",
      eventSeq: "Seq",
      eventTime: "Zeitpunkt",
      effectiveYes: "ja",
      effectiveNo: "nein",
      actionPreview: "Stand ansehen",
      actionRollbackAtomic: "Atomic rollback",
      actionRollbackGroup: "Gruppen rollback",
      actionHardReset: "Import zurückrollen",
      leavePreview: "Zurueck zum Live-Stand",
      loading: "Historie wird geladen...",
      noSeason: "Bitte zuerst eine Saison auswaehlen.",
      rollbackModeAtomic: "Atomic rollback",
      rollbackModeGrouped: "Gruppierter rollback",
      rollbackConfirmTitle: "Rollback bestaetigen?",
      rollbackConfirmAtomicBody:
        "Der betroffene Lauf wird als zurueckgerollt markiert. Die Wertung wird danach aus dem Live-Stand neu aufgebaut.",
      rollbackConfirmGroupBody:
        "Alle aktiven Laufereignisse der Importgruppe werden zurueckgerollt und der Batch als rolled_back markiert.",
      hardResetConfirmTitle: "Zurücksetzen bestätigen",
      hardResetConfirmBody:
        "Dieser Import sowie alle späteren Imports und Korrekturen werden dauerhaft gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.",
      hardResetConfirmFile: (fileName: string) => `Datei: ${fileName}`,
      actionBlockedPreview: "Aktion nur aus dem Live-Stand moeglich.",
      sourceFile: "Dateiname",
      importedAt: "Importiert am",
      state: "Status",
      rows: "Zeilen",
      rollback: "Rollback",
      noImports: "Noch keine Importe vorhanden.",
      noAuditRows: "Keine Korrekturen protokolliert.",
      importRollbackConfirmTitle: "Import zurückrollen?",
      importRollbackConfirmBody:
        "Die Ergebnisse dieses Imports werden aus der Wertung genommen. Spätere Imports anderer Kategorien bleiben unberührt.",
      rollbackConfirmBodyWithCount: (count: number) =>
        `Die Ergebnisse aller ${count} Läufe aus dieser Datei werden aus der Wertung entfernt und neu berechnet.`,
      rollbackDone: (count: number) => `Datei-Import wurde zurückgenommen (${count} Läufe).`,
      rolledBack: "zurückgerollt",
      active: "aktiv",
    },
    season: {
      title: "Saison verwalten",
      subtitle: "Wählen Sie eine bestehende Saison aus oder legen Sie eine neue Saison an.",
      placeholder: "Bitte Saison auswählen oder neu anlegen.",
      createTitle: "Neue Saison",
      createLabel: "Saisonname",
      createOpenAction: "Saison anlegen",
      createAction: "Neue Saison erstellen",
      openAction: "Öffnen",
      deleteAction: "Löschen",
      resetAction: "Zurücksetzen",
      importAction: "Saison importieren",
      exportAction: "Datensicherung",
      exportPdfAction: "PDF",
      exportExcelAction: "Excel",
      noSeasons: "Noch keine Saisons vorhanden.",
      activeTag: "Aktiv",
      importedEvents: "Importierte Läufe",
      lastModified: "Zuletzt geändert",
      actions: "Aktionen",
      deleteConfirmTitle: "Saison löschen?",
      deleteConfirmBody: "Diese Saison wird dauerhaft entfernt.",
      deleteConfirmTypePrompt: (label: string) =>
        `Bitte geben Sie "${label}" ein um die Saison unwiderruflich zu löschen.`,
      deleteConfirmInputLabel: "Saisonname zur Bestätigung",
      resetConfirmTitle: "Saison zurücksetzen?",
      resetConfirmBody: "Alle Event-Daten der Saison werden gelöscht.",
      exportHint: "Export folgt in F-TS07/F-TS08.",
      importHint: "Import folgt in F-TS07.",
      createdDone: (label: string) => `Saison "${label}" angelegt.`,
      deletedDone: "Saison gelöscht.",
      resetDone: "Saison wurde zurückgesetzt.",
      openedDone: (label: string) => `Saison "${label}" geöffnet.`,
      nameHeader: "Name",
      createPlaceholder: "z. B. Stundenlauf 2027",
      activeSeasonTitle: "Aktive Saison",
      noActiveSeason: "Noch keine Saison geoeffnet.",
      backupNote:
        "Backup-Import und Backup-Export sind in Phase 1 bereits sichtbar, werden aber noch vom Mock-AppApi beantwortet.",
      existingSeasonsTitle: "Bestehende Saisons",
      existingSeasonsDescription: "Alle vorhandenen Saisons stehen hier direkt zum Oeffnen oder Verwalten bereit.",
      loading: "Saisons werden geladen...",
      enterSeasonName: "Bitte einen Saisonnamen eingeben.",
    },
    corrections: {
      title: "Korrekturen",
      subtitle: "Wählen Sie eine Kategorie aus und korrigieren Sie Teilnehmerdaten oder die Wertungsstellung.",
      guidance:
        "Hinweis: Namen oder Vereine anklicken, um Korrekturen zu starten. Über a.W. setzen oder entfernen Sie Teams als außer Wertung. Weitere Korrektur-Funktionen folgen hier.",
      noSeason: "Bitte zuerst eine Saison auswählen.",
      loading: "Korrekturen werden geladen...",
      correctionModalTitle: "Daten korrigieren",
      memberALabel: "Teilnehmende A",
      memberBLabel: "Teilnehmende B",
      fieldName: "Name",
      fieldYob: "Jahrgang",
      fieldClub: "Verein",
      errorRequired: "Name und Jahrgang sind für die Korrektur erforderlich.",
      saveSuccess: "Teilnehmerdaten gespeichert.",
      save: "Speichern",
      cancel: "Abbrechen",
    },
  },
  category: {
    "hour:men": "60 Minuten Herren",
    "hour:women": "60 Minuten Damen",
    "hour:couples_men": "60 Minuten Paare Herren",
    "hour:couples_women": "60 Minuten Paare Damen",
    "hour:couples_mixed": "60 Minuten Paare Mixed",
    "half_hour:men": "30 Minuten Herren",
    "half_hour:women": "30 Minuten Damen",
    "half_hour:couples_men": "30 Minuten Paare Herren",
    "half_hour:couples_women": "30 Minuten Paare Damen",
    "half_hour:couples_mixed": "30 Minuten Paare Mixed",
  } as Record<string, string>,
  actions: {
    save: "Speichern",
    close: "Schließen",
    apply: "Übernehmen",
  },
  identityModal: {
    title: "Identität korrigieren",
    givenName: "Vorname",
    familyName: "Nachname",
    displayName: "Anzeigename",
    yob: "Jahrgang",
    club: "Verein",
  },
  mergeModal: {
    title: "Duplikate zusammenführen",
    survivor: "Ziel-Team",
    absorbed: "Aufzulösendes Team",
    help: "Alle übertragbaren Einträge werden vom aufzulösenden Team zum Ziel-Team verschoben.",
  },
  confidence: {
    high: "hoch",
    medium: "mittel",
    low: "niedrig",
  },
  app: {
    errorTitle: "App-Fehler",
  },
  update: {
    available: "Neue Version verfuegbar.",
    refresh: "Aktualisieren",
  },
  importCandidate: {
    incomingLabel: "Neu:",
    existingLabel: "Bestand:",
    participantA: "Teilnehmende A",
    participantB: "Teilnehmende B",
    name: "Name",
    yob: "Jahrgang",
    club: "Verein",
    assignmentHint: "Bei Auswahl werden die eingehenden Ergebnisse dieser Person bzw. diesem Team zugeordnet.",
    selectedDisplayName: (name: string, suffix: string) => `${name} - ${suffix}`,
  },
} as const;
